/*
 * ipc_protocol.h - Production Microkernel IPC Protocol
 *
 * Defines message types and data structures for service communication:
 *   GUI Service     ← Hardware driver (keyboard/mouse/display)
 *   Console Service ← Text rendering, ANSI parsing, buffer management
 *   TTY Service     ← Line discipline, echo, job control, sessions
 *   Shell/Apps      ← User applications
 *
 * Architecture:
 *   Kernel → Console (boot messages)
 *   GUI → Console (keyboard/mouse events)
 *   Console → GUI (rendering commands)
 *   TTY ↔ Console (text I/O)
 *   Shell → TTY (read/write/ioctl)
 */

#ifndef IPC_PROTOCOL_H
#define IPC_PROTOCOL_H

#include <stdint.h>

/* ============================================================================
 * Service Endpoint Identifiers
 * ============================================================================ */

#define SERVICE_SHELL      1   /* Shell application (moonsh) */
#define SERVICE_MEM        2   /* Memory server */
#define SERVICE_CONSOLE    3   /* Console text rendering service (was qrexec) */
#define SERVICE_TTY        4   /* TTY line discipline service (was adminvm) */
#define SERVICE_GUI        10  /* GUI/Display hardware driver */

/* ============================================================================
 * Message Type Definitions
 * ============================================================================ */

/* GUI → Console: Input events from hardware */
#define MSG_GUI_KEY_EVENT       0x1000  /* Keyboard event */
#define MSG_GUI_MOUSE_EVENT     0x1001  /* Mouse movement/button */
#define MSG_GUI_READY           0x1002  /* GUI initialized, ready for rendering */

/* Console → GUI: Rendering commands */
#define MSG_CONSOLE_PUTC        0x2000  /* Draw single character */
#define MSG_CONSOLE_FILL        0x2001  /* Fill rectangle */
#define MSG_CONSOLE_SCROLL      0x2002  /* Scroll region */
#define MSG_CONSOLE_CURSOR      0x2003  /* Move cursor */
#define MSG_CONSOLE_CLEAR       0x2004  /* Clear screen */

/* TTY ↔ Console: Character I/O */
#define MSG_TTY_WRITE           0x3000  /* TTY → Console: write chars */
#define MSG_TTY_READ            0x3001  /* TTY → Console: request input */
#define MSG_TTY_IOCTL           0x3002  /* TTY control (termios) */
#define MSG_CONSOLE_INPUT       0x3100  /* Console → TTY: input available */

/* Shell/App ↔ TTY: Application I/O */
#define MSG_APP_OPEN            0x4000  /* Open TTY */
#define MSG_APP_CLOSE           0x4001  /* Close TTY */
#define MSG_APP_READ            0x4002  /* Read from TTY */
#define MSG_APP_WRITE           0x4003  /* Write to TTY */
#define MSG_APP_IOCTL           0x4004  /* TTY ioctl */

/* Kernel → Console: Early boot messages */
#define MSG_KERNEL_BOOT_LOG     0x5000  /* Kernel boot message */

/* Generic responses */
#define MSG_ACK                 0xF000  /* Operation acknowledged */
#define MSG_ERROR               0xF001  /* Operation failed */

/* ============================================================================
 * Common Message Header
 * ============================================================================ */

/* Message header for reliable request-response matching.
 * All request-response messages should include this header.
 * msg_id is generated by the sender and echoed in the response. */
typedef struct {
    uint32_t msg_type;      /* Message type (MSG_* constants) */
    uint32_t msg_id;        /* Sequence number for request-response matching */
} ipc_msg_header_t;

/* ============================================================================
 * Key Event Structures
 * ============================================================================ */

/* Key modifier flags */
#define KEY_MOD_SHIFT   (1 << 0)
#define KEY_MOD_CTRL    (1 << 1)
#define KEY_MOD_ALT     (1 << 2)
#define KEY_MOD_META    (1 << 3)

/* Key event (GUI → Console) */
typedef struct {
    uint32_t msg_type;      /* MSG_GUI_KEY_EVENT */
    uint32_t msg_id;        /* Sequence number for request-response matching */
    uint32_t keycode;       /* Scan code or key value */
    uint32_t ascii;         /* ASCII character (0 if non-printable) */
    uint32_t modifiers;     /* KEY_MOD_* flags */
    uint32_t pressed;       /* 1 = key down, 0 = key up */
} msg_key_event_t;

/* Mouse event (GUI → Console) */
typedef struct {
    uint32_t msg_type;      /* MSG_GUI_MOUSE_EVENT */
    uint32_t msg_id;        /* Sequence number for request-response matching */
    int32_t  dx;            /* Relative X movement */
    int32_t  dy;            /* Relative Y movement */
    uint32_t buttons;       /* Button state: bit0=left, bit1=right, bit2=middle */
    int32_t  x;             /* Absolute X position (0-799) */
    int32_t  y;             /* Absolute Y position (0-599) */
} msg_mouse_event_t;

/* ============================================================================
 * Console Rendering Structures
 * ============================================================================ */

/* Console → GUI: Draw single character */
typedef struct {
    uint32_t msg_type;      /* MSG_CONSOLE_PUTC */
    uint32_t msg_id;        /* Sequence number for request-response matching */
    uint32_t x;             /* Character column (0-99) */
    uint32_t y;             /* Character row (0-74) */
    uint32_t ch;            /* ASCII character */
    uint32_t fg_color;      /* Foreground RGB (0xRRGGBB) */
    uint32_t bg_color;      /* Background RGB */
} msg_console_putc_t;

/* Console → GUI: Fill rectangle */
typedef struct {
    uint32_t msg_type;      /* MSG_CONSOLE_FILL */
    uint32_t msg_id;        /* Sequence number for request-response matching */
    uint32_t x;             /* Left edge (pixels) */
    uint32_t y;             /* Top edge (pixels) */
    uint32_t width;         /* Width (pixels) */
    uint32_t height;        /* Height (pixels) */
    uint32_t color;         /* Fill color RGB */
} msg_console_fill_t;

/* Console → GUI: Scroll screen region */
typedef struct {
    uint32_t msg_type;      /* MSG_CONSOLE_SCROLL */
    uint32_t lines;         /* Number of lines to scroll up */
    uint32_t top;           /* Top row of scroll region */
    uint32_t bottom;        /* Bottom row of scroll region */
} msg_console_scroll_t;

/* Console → GUI: Move cursor */
typedef struct {
    uint32_t msg_type;      /* MSG_CONSOLE_CURSOR */
    uint32_t x;             /* Column */
    uint32_t y;             /* Row */
    uint32_t visible;       /* 1 = show cursor, 0 = hide */
} msg_console_cursor_t;

/* ============================================================================
 * TTY I/O Structures
 * ============================================================================ */

#define TTY_BUF_SIZE 16   /* Max data per IPC message (must fit 32-byte inline transfer) */

/* TTY → Console: Write characters */
typedef struct {
    uint32_t msg_type;      /* MSG_TTY_WRITE */
    uint32_t tty_id;        /* TTY number (0-11 for F1-F12) */
    uint32_t len;           /* Number of bytes */
    char     data[TTY_BUF_SIZE];
} msg_tty_write_t;

/* Console → TTY: Input available */
typedef struct {
    uint32_t msg_type;      /* MSG_CONSOLE_INPUT */
    uint32_t tty_id;        /* TTY number */
    uint32_t len;           /* Number of bytes */
    char     data[TTY_BUF_SIZE];
} msg_console_input_t;

/* TTY ioctl commands */
#define TTY_IOCTL_ECHO          0x01    /* Enable/disable echo */
#define TTY_IOCTL_CANON         0x02    /* Enable/disable canonical mode */
#define TTY_IOCTL_RAW           0x03    /* Enable raw mode */
#define TTY_IOCTL_CLEAR         0x04    /* Clear screen */
#define TTY_IOCTL_SWITCH        0x05    /* Switch active TTY */

typedef struct {
    uint32_t msg_type;      /* MSG_TTY_IOCTL or MSG_APP_IOCTL */
    uint32_t tty_id;        /* TTY number */
    uint32_t cmd;           /* TTY_IOCTL_* */
    uint32_t arg;           /* Command argument */
} msg_tty_ioctl_t;

/* ============================================================================
 * Application I/O Structures
 * ============================================================================ */

/* App → TTY: Open TTY */
typedef struct {
    uint32_t msg_type;      /* MSG_APP_OPEN */
    uint32_t msg_id;        /* Sequence number for request-response matching */
    uint32_t tty_id;        /* TTY to open (0-11) */
    uint32_t flags;         /* Open flags (unused) */
} msg_app_open_t;

/* App → TTY: Read from TTY */
typedef struct {
    uint32_t msg_type;      /* MSG_APP_READ */
    uint32_t msg_id;        /* Sequence number for request-response matching */
    uint32_t tty_id;        /* TTY number */
    uint32_t max_len;       /* Max bytes to read */
} msg_app_read_t;

/* TTY → App: Read response */
typedef struct {
    uint32_t msg_type;      /* MSG_ACK */
    uint32_t msg_id;        /* Echo of request msg_id for matching */
    uint32_t len;           /* Bytes read */
    char     data[TTY_BUF_SIZE];
} msg_app_read_resp_t;

/* App → TTY: Write to TTY */
typedef struct {
    uint32_t msg_type;      /* MSG_APP_WRITE */
    uint32_t msg_id;        /* Sequence number for request-response matching */
    uint32_t tty_id;        /* TTY number */
    uint32_t len;           /* Bytes to write */
    char     data[TTY_BUF_SIZE];
} msg_app_write_t;

/* ============================================================================
 * Kernel Boot Log Structure
 * ============================================================================ */

#define KERNEL_LOG_SIZE 24  /* Max data per boot log message (32 - 8 header bytes) */

/* Kernel → Console: Boot message (sent during early init) */
typedef struct {
    uint32_t msg_type;      /* MSG_KERNEL_BOOT_LOG */
    uint32_t len;           /* Message length */
    char     data[KERNEL_LOG_SIZE];
} msg_kernel_boot_log_t;

/* ============================================================================
 * Generic Response
 * ============================================================================ */

typedef struct {
    uint32_t msg_type;      /* MSG_ACK or MSG_ERROR */
    uint32_t msg_id;        /* Echo of request msg_id for matching */
    uint32_t status;        /* Status code (0 = success) */
    uint32_t data;          /* Optional response data */
} msg_response_t;

/* ============================================================================
 * Union for all message types (for easy casting)
 * ============================================================================ */

typedef union {
    uint32_t                msg_type;
    msg_key_event_t         key_event;
    msg_mouse_event_t       mouse_event;
    msg_console_putc_t      console_putc;
    msg_console_fill_t      console_fill;
    msg_console_scroll_t    console_scroll;
    msg_console_cursor_t    console_cursor;
    msg_tty_write_t         tty_write;
    msg_console_input_t     console_input;
    msg_tty_ioctl_t         tty_ioctl;
    msg_app_open_t          app_open;
    msg_app_read_t          app_read;
    msg_app_read_resp_t     app_read_resp;
    msg_app_write_t         app_write;
    msg_kernel_boot_log_t   kernel_boot_log;
    msg_response_t          response;
} ipc_message_t;

#endif /* IPC_PROTOCOL_H */
