/* initrd.c - initrd frame pool for ELF loading
 *
 * The initrd is embedded as a byte array in initrd_data.c (generated by
 * tools/mkinitrd.sh). This file maps the initrd into the frame pool so
 * the ELF loader can access it via frame IDs.
 */
#include "initrd.h"
#include "caps.h"

extern uint8_t frame_bitmap[];
extern uint32_t initrd_num_frames;

void initrd_init(void)
{
    /* The initrd data is already at initrd_data (identity mapped in physical
     * memory at V2_FRAME_PHYS_BASE + frame_id * 4096 via l0_frames).
     *
     * The initrd occupies frames 1..initrd_num_frames (frame 0 is reserved).
     * We just need to mark those frames as used in the frame bitmap so they
     * don't get allocated for other purposes.
     *
     * Note: frame_bitmap[0] is already reserved (kernel). Frames 1..N are
     * used by initrd. We mark them as used (0 = used in bitmap).
     */
    for (uint32_t i = 1; i <= initrd_num_frames && i < V2_FRAMES_MAX; i++) {
        frame_bitmap[i] = 0; /* mark as used */
}
}