/* initrd.c - initrd blob accessor for ELF loading (Stage 3).
 *
 * The initrd is embedded as a byte array in initrd_data.c (generated by
 * tools/mkinitrd.sh), living in the kernel image (.data, S-accessible).
 * It does NOT consume frame-pool frames: the ELF loader (elf.c) copies
 * segment bytes out of initrd_data into freshly allocated frames, so the
 * pool stays free for dynamic allocation. initrd_init is therefore a
 * no-op (frame 0's reservation lives in frame_pool_init, kboot.c).
 *
 * Index 0 is mem_server.elf (REQUIRED, enforced by mkinitrd.sh); the
 * kernel SPAWNs it into thread 2 at boot.
 */
#include "initrd.h"

void initrd_init(void)
{
    /* No-op by design (see above). References keep the symbols live for
     * the linker gate without emitting code. */
    (void)initrd_data;
    (void)initrd_size;
    (void)initrd_num_frames;
    (void)initrd_files;
    (void)initrd_num_files;
}

/* Look up initrd entry idx: fail-closed NULL/out checks + overflow-safe
 * bounds against initrd_size. Returns 0 with (*out_ptr, *out_size) on
 * success, -1 otherwise. */
int initrd_lookup(uint32_t idx, const uint8_t **out_ptr, uint32_t *out_size)
{
    uint32_t off, sz;
    if (!out_ptr || !out_size)
        return -1;
    *out_ptr = 0;
    *out_size = 0;
    if (idx >= initrd_num_files)
        return -1;
    off = initrd_files[idx].offset;
    sz = initrd_files[idx].size;
    if (sz == 0 || sz > initrd_size || off > initrd_size - sz)
        return -1;
    *out_ptr = &initrd_data[off];
    *out_size = sz;
    return 0;
}
