#!/bin/bash
# mkinitrd.sh - Build initrd from userspace ELFs
# Outputs kernel/initrd_data.c for embedding in kernel

set -e

OUT_DIR="kernel"
INITRD_C="$OUT_DIR/initrd_data.c"
INITRD_H="$OUT_DIR/initrd.h"
ELF_DIR="userspace/build"

# ELF binaries to include (in order)
ELFS=(
    "moonsh.elf"
    "ls.elf"
    "cat.elf"
    "write.elf"
    "rm.elf"
    "echo.elf"
)

echo "Building initrd from userspace ELFs..."

# Create initrd image
TMP_INITRD=$(mktemp)
for elf in "${ELFS[@]}"; do
    if [ -f "$ELF_DIR/$elf" ]; then
        echo "  Adding $elf..."
        # Pad to 4096 bytes
        cat "$ELF_DIR/$elf" >> "$TMP_INITRD"
        SIZE=$(stat -c%s "$ELF_DIR/$elf")
        PAD=$((4096 - (SIZE % 4096)))
        if [ $PAD -ne 4096 ]; then
            dd if=/dev/zero bs=$PAD count=1 >> "$TMP_INITRD" 2>/dev/null
        fi
    else
        echo "  WARNING: $elf not found, skipping"
    fi
done

# Generate C array
INITRD_SIZE=$(stat -c%s "$TMP_INITRD")
NUM_FRAMES=$(( (INITRD_SIZE + 4095) / 4096 ))

echo "Generating $INITRD_C..."
echo "// Auto-generated by mkinitrd.sh" > "$INITRD_C"
echo "#include <stdint.h>" >> "$INITRD_C"
echo "" >> "$INITRD_C"
echo "uint8_t initrd_data[] __attribute__((aligned(4096))) = {" >> "$INITRD_C"

# Convert binary to hex (flat array, no nested arrays)
od -An -tx1 -v "$TMP_INITRD" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]\+$//' | sed 's/[[:space:]]\+/, 0x/g' | sed 's/^/  0x/' | sed 's/$/,/' >> "$INITRD_C"

echo "};" >> "$INITRD_C"
echo "" >> "$INITRD_C"
echo "uint32_t initrd_size = $INITRD_SIZE;" >> "$INITRD_C"
echo "uint32_t initrd_num_frames = $NUM_FRAMES;" >> "$INITRD_C"

# Generate header
echo "#ifndef INITRD_H" > "$INITRD_H"
echo "#define INITRD_H" >> "$INITRD_H"
echo "#include <stdint.h>" >> "$INITRD_H"
echo "extern uint8_t initrd_data[];" >> "$INITRD_H"
echo "extern uint32_t initrd_size;" >> "$INITRD_H"
echo "extern uint32_t initrd_num_frames;" >> "$INITRD_H"
echo "#endif" >> "$INITRD_H"

rm -f "$TMP_INITRD"
echo "Done: $INITRD_SIZE bytes ($NUM_FRAMES frames)"