#!/bin/bash
# mkinitrd.sh - Build initrd from userspace ELFs
# Outputs kernel/initrd_data.c + kernel/initrd.h for embedding in kernel.
#
# Stage 3: mem_server.elf is FIRST (initrd index 0) and REQUIRED — the
# kernel SPAWNs index 0 into thread 2's VSpace at boot. The remaining ELFs
# are optional shell utilities (missing ones warn, as before).
#
# Layout: each ELF padded to a 4096 multiple; initrd_files[] records the
# real (unpadded) size so the ELF loader bounds-checks against it. The blob
# lives in the kernel image (.data); it does NOT consume frame-pool frames.

set -e

OUT_DIR="kernel"
INITRD_C="$OUT_DIR/initrd_data.c"
INITRD_H="$OUT_DIR/initrd.h"
ELF_DIR="userspace/build"

# ELF binaries to include (in order). Index 0 must be mem_server.elf.
# Every entry here must have a matching build rule in userspace/Makefile;
# do not list aspirational binaries (a missing entry used to warn forever).
ELFS=(
    "mem_server.elf"
    "qrexec.elf"
    "adminvm.elf"
    "firewall.elf"
    "net.elf"
    "moonsh.elf"
    "ls.elf"
    "cat.elf"
    "vault.elf"
    "cryptblk.elf"
)
REQUIRED="mem_server.elf"

echo "Building initrd from userspace ELFs..."

# Create initrd image, tracking offsets/sizes for the TOC
TMP_INITRD=$(mktemp)
OFFSET=0
NAMES=()
OFFSETS=()
SIZES=()
for elf in "${ELFS[@]}"; do
    if [ -f "$ELF_DIR/$elf" ]; then
        echo "  Adding $elf..."
        SIZE=$(stat -c%s "$ELF_DIR/$elf")
        # Pad to 4096 bytes
        cat "$ELF_DIR/$elf" >> "$TMP_INITRD"
        PAD=$((4096 - (SIZE % 4096)))
        if [ $PAD -ne 4096 ]; then
            dd if=/dev/zero bs=$PAD count=1 >> "$TMP_INITRD" 2>/dev/null
            OFFSET_NEXT=$((OFFSET + SIZE + PAD))
        else
            OFFSET_NEXT=$((OFFSET + SIZE))
        fi
        NAMES+=("$elf")
        OFFSETS+=("$OFFSET")
        SIZES+=("$SIZE")
        OFFSET=$OFFSET_NEXT
    else
        if [ "$elf" = "$REQUIRED" ]; then
            echo "  ERROR: required $elf not found (build it: make -C userspace build/mem_server.elf)"
            rm -f "$TMP_INITRD"
            exit 1
        fi
        echo "  WARNING: $elf not found, skipping"
    fi
done

# Generate header FIRST (initrd_data.c includes it for the TOC type)
NUM_FILES=${#NAMES[@]}
{
echo "#ifndef INITRD_H"
echo "#define INITRD_H"
echo "#include <stdint.h>"
echo "typedef struct { const char *name; uint32_t offset; uint32_t size; } initrd_file_t;"
echo "extern uint8_t initrd_data[];"
echo "extern uint32_t initrd_size;"
echo "extern uint32_t initrd_num_frames;"
echo "extern initrd_file_t initrd_files[];"
echo "extern uint32_t initrd_num_files;"
echo "void initrd_init(void);"
echo "int initrd_lookup(uint32_t idx, const uint8_t **out_ptr, uint32_t *out_size);"
echo "#endif"
} > "$INITRD_H"
echo "Generating $INITRD_H ($NUM_FILES files)..."

# Generate C array
INITRD_SIZE=$(stat -c%s "$TMP_INITRD")
NUM_FRAMES=$(( (INITRD_SIZE + 4095) / 4096 ))

echo "Generating $INITRD_C..."
echo "// Auto-generated by mkinitrd.sh" > "$INITRD_C"
echo "#include <stdint.h>" >> "$INITRD_C"
echo "#include \"initrd.h\"" >> "$INITRD_C"
echo "" >> "$INITRD_C"
echo "uint8_t initrd_data[] __attribute__((aligned(4096))) = {" >> "$INITRD_C"

# Convert binary to hex (flat array, no nested arrays)
od -An -tx1 -v "$TMP_INITRD" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]\+$//' | sed 's/[[:space:]]\+/, 0x/g' | sed 's/^/  0x/' | sed 's/$/,/' >> "$INITRD_C"

echo "};" >> "$INITRD_C"
echo "" >> "$INITRD_C"
echo "uint32_t initrd_size = $INITRD_SIZE;" >> "$INITRD_C"
echo "uint32_t initrd_num_frames = $NUM_FRAMES;" >> "$INITRD_C"
echo "" >> "$INITRD_C"
echo "initrd_file_t initrd_files[] = {" >> "$INITRD_C"
for i in "${!NAMES[@]}"; do
    echo "  { \"${NAMES[$i]}\", ${OFFSETS[$i]}, ${SIZES[$i]} }," >> "$INITRD_C"
done
echo "};" >> "$INITRD_C"
echo "uint32_t initrd_num_files = $NUM_FILES;" >> "$INITRD_C"

rm -f "$TMP_INITRD"
echo "Done: $INITRD_SIZE bytes ($NUM_FRAMES frames, $NUM_FILES files)"
