/* userspace/initrd_vfs.h - Minimal VFS abstraction for initrd access.
 * Allows shell to list programs and query metadata (size, type).
 * Kernel provides initrd through hidden symbols (initrd_data, initrd_files, etc.)
 * This header exposes them via weak symbols for optional linking.
 *
 * Design: Freestanding implementation for shell.c to discover/execute programs.
 * Types: FILE_TYPE_ELF (executable binary), FILE_TYPE_DATA (blobs).
 * No dynamic allocation: all metadata is static from build time (mkinitrd.sh).
 */

#ifndef INITRD_VFS_H
#define INITRD_VFS_H

#include <stdint.h>

/* Initrd file metadata (populated by tools/mkinitrd.sh) */
typedef struct
{
    uint32_t offset; /* Byte offset in initrd blob */
    uint32_t size;   /* Size in bytes */
} initrd_file_entry_t;

/* Weak symbols provided by kernel (defined in kernel/initrd_data.c, generated by mkinitrd.sh).
 * Userspace ELF linking will NOT have these (NULL); kernel image gets the real definitions.
 * Kernel passes initrd data via mapping a frame containing initrd metadata into a specific VPN,
 * or via IPC message from mem_server. For now, assume weak symbols resolve to NULL in userspace. */
__attribute__((weak)) extern const uint8_t initrd_data[];
__attribute__((weak)) extern const uint32_t initrd_size;
__attribute__((weak)) extern const uint32_t initrd_num_files;
__attribute__((weak)) extern const initrd_file_entry_t initrd_files[];

/* File type constants (for future extension) */
#define INITRD_FILE_UNKNOWN 0
#define INITRD_FILE_ELF 1
#define INITRD_FILE_DATA 2

/* File entry: name, index, size (name is NOT stored in binary; instead,
 * mkinitrd.sh generates a name-to-index mapping that the shell must hardcode
 * or discover via IPC. For MVP, we hardcode known programs. */
typedef struct
{
    const char *name; /* Program name (e.g., "mem_server.elf") */
    uint32_t idx;     /* Index into initrd_files[] */
    uint32_t size;    /* Size in bytes */
    int type;         /* INITRD_FILE_ELF or INITRD_FILE_DATA */
    int executable;   /* 1 if this is a runnable program (ELF) */
} initrd_program_t;

/* Known programs: hardcoded by build system. This table is generated by
 * tools/mkinitrd.sh based on the order of inputs. The shell uses this to
 * resolve program names ("hello", "cat", "echo") to initrd indices.
 *
 * Example (from mkinitrd.sh output):
 *   Index 0: mem_server.elf
 *   Index 1: qrexec_server.elf
 *   Index 2: adminvm.elf
 *   ...
 *   Index N: hello.elf
 *   Index N+1: cat.elf
 *
 * We'll define this table in shell.c after querying the build output.
 * For now, provide lookup functions. */

/* String comparison (no libc in freestanding builds: roll our own). */
static inline int initrd_streq(const char *a, const char *b)
{
    if (!a || !b)
        return 0;
    while (*a && *a == *b)
    {
        a++;
        b++;
    }
    return *a == *b;
}

/* Look up program by name. Returns index (>= 0) on success, -1 on not found.
 * Indices mirror tools/mkinitrd.sh ELFS order (see shell_programs.h);
 * unpacked names (qrexec/adminvm/..., ls/cat/echo/hello) resolve to -1. */
static inline int initrd_find_program(const char *name)
{
    if (!name || *name == '\0')
        return -1;

    if (initrd_streq(name, "mem_server.elf"))
        return 0;
    if (initrd_streq(name, "moonsh.elf"))
        return 1;
    if (initrd_streq(name, "console.elf"))
        return 3;
    if (initrd_streq(name, "tty.elf"))
        return 4;
    if (initrd_streq(name, "gui.elf"))
        return 10;

    return -1; /* not found (includes UNUSED holes 2, 5-9) */
}

/* Get size of program by index. Returns size (> 0) on success, 0 on invalid. */
static inline uint32_t initrd_get_size(unsigned int idx)
{
    /* Check bounds: index must be < initrd_num_files */
    if (initrd_files && initrd_num_files && idx < initrd_num_files)
    {
        return initrd_files[idx].size;
    }
    return 0; /* invalid or not found */
}

/* List all programs in initrd. Calls callback for each entry.
 * Useful for shell "ls" command. Callback returns 0 to continue, non-zero to stop. */
typedef int (*initrd_list_callback_t)(const char *name, uint32_t idx, uint32_t size);

static inline int initrd_list_programs(initrd_list_callback_t callback)
{
    /* Sizes are unknown without the kernel TOC (initrd_files is weak-NULL
     * in userspace ELFs): report 0 and let callers query initrd_get_size.
     * Names/indices mirror tools/mkinitrd.sh ELFS order. */
    if (!callback)
        return -1;

    if (callback("mem_server.elf", 0, 0))
        return 0;
    if (callback("moonsh.elf", 1, 0))
        return 0;
    if (callback("console.elf", 3, 0))
        return 0;
    if (callback("tty.elf", 4, 0))
        return 0;
    if (callback("gui.elf", 10, 0))
        return 0;

    return 0;
}

/* Check if a program is loadable (basic validation without ELF parsing).
 * Returns 1 if loadable, 0 if invalid/not_found. */
static inline int initrd_is_loadable(unsigned int idx)
{
    uint32_t size = initrd_get_size(idx);
    return size > 64; /* ELF header minimum */
}

#endif /* INITRD_VFS_H */
